# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointment_reschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Buyer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.Property'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Seller'),
        ),
    ]
