# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_auto_20201118_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='User.Buyer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_id', to='Property.Property'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='User.Seller'),
        ),
    ]
