# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_auto_20201118_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='response',
            field=models.CharField(choices=[('accept', 'Accept'), ('reschedule', 'Reschedule'), ('reject', 'Reject')], default=None, max_length=15, null=True),
        ),
    ]
