# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200831_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
