# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200904_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
