# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-06 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200906_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='location',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='middle_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
