# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-06 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200906_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='middle_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
