# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-14 06:16
from __future__ import unicode_literals

import EstateByTheOwner.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1, 0)])),
                ('beds', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0, 0)])),
                ('bath', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0, 99)])),
                ('size', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(10, 0)])),
                ('description', models.CharField(max_length=1000, null=True)),
                ('propertytype', models.CharField(choices=[('townhouse', 'Townhouse'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], default='townhouse', max_length=2)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=EstateByTheOwner.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
            options={
                'db_table': 'property_img',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(to='Property.PropertyImages'),
        ),
    ]
