# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 22:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1, 0)])),
                ('beds', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0, 0)])),
                ('bath', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0, 99)])),
                ('size', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(10, 0)])),
                ('description', models.CharField(max_length=1000, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
    ]
