# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='neighbourhood',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='paytype',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=2),
        ),
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
