# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_auto_20200819_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='paytype',
            new_name='propertytype',
        ),
    ]
