# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 06:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_auto_20200914_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address1',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bath',
            field=models.FloatField(db_index=True, default=1.0, validators=[django.core.validators.MinValueValidator(0, 99)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.FloatField(db_index=True, default=1.0, validators=[django.core.validators.MinValueValidator(0, 0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(db_index=True, default=1.0, validators=[django.core.validators.MinValueValidator(1, 0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertytype',
            field=models.CharField(choices=[('townhouse', 'Townhouse'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], db_index=True, default='townhouse', max_length=2),
        ),
    ]
