# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 21:40
from __future__ import unicode_literals

import EstateByTheOwner.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_auto_20200920_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_ico',
            field=models.ImageField(default=None, null=True, storage=EstateByTheOwner.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='file',
            field=models.ImageField(storage=EstateByTheOwner.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
