# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-26 09:55
from __future__ import unicode_literals

import EstateByTheOwner.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_auto_20200920_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(default=None, null=True, storage=EstateByTheOwner.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
