# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_property_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertytype',
            field=models.CharField(choices=[('townhouse', 'Townhouse'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('commercial', 'Commercial')], db_index=True, default='townhouse', max_length=50),
        ),
    ]
