# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_auto_20201011_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='Property.Property'),
        ),
    ]
